# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(default=-1, primary_key=True, serialize=False, verbose_name='book id')),
                ('title', models.CharField(max_length=200)),
                ('pub_year', models.IntegerField(default=1970, verbose_name='publication year')),
                ('author', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Explaination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField(default=-1, verbose_name='explaination id')),
                ('e_author', models.CharField(max_length=200)),
                ('page', models.IntegerField(default=1, verbose_name='page')),
                ('karma', models.IntegerField(default=1, verbose_name='karma')),
                ('status', models.CharField(max_length=7)),
                ('e_content', models.CharField(max_length=5000)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookswiki.Book')),
            ],
        ),
    ]
