# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswiki', '0002_auto_20171228_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='books',
            field=models.ManyToManyField(to='bookswiki.Book'),
        ),
    ]
