# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookswiki', '0003_auto_20171228_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='books',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
