# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookswiki', '0005_auto_20171230_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explaination',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='bookswiki.Vote'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='status',
            field=models.CharField(default='neutral', max_length=7),
        ),
    ]
