# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswiki', '0006_auto_20171230_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explaination',
            name='status',
            field=models.CharField(default='neutral', max_length=7),
        ),
    ]
