# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-13 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswiki', '0009_auto_20180108_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imagelink',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
