# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookswiki', '0010_book_imagelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='explaination',
            name='e_author',
        ),
        migrations.RemoveField(
            model_name='explaination',
            name='e_content',
        ),
        migrations.RemoveField(
            model_name='explaination',
            name='e_id',
        ),
        migrations.RemoveField(
            model_name='explaination',
            name='karma',
        ),
        migrations.RemoveField(
            model_name='explaination',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='explaination',
            name='content',
            field=models.CharField(default='default', max_length=10000),
        ),
        migrations.AddField(
            model_name='explaination',
            name='date',
            field=models.CharField(default='01-01-1970', max_length=10),
        ),
        migrations.AddField(
            model_name='explaination',
            name='user',
            field=models.CharField(default='defuser', max_length=64),
        ),
        migrations.AddField(
            model_name='vote',
            name='type',
            field=models.CharField(default='neut', max_length=4),
        ),
        migrations.AlterField(
            model_name='explaination',
            name='book',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='explaination',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='explaination',
            field=models.IntegerField(default=-1, verbose_name='expid'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookswiki.Vote'),
        ),
    ]
