# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswiki', '0011_auto_20180214_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vote',
        ),
        migrations.AddField(
            model_name='vote',
            name='username',
            field=models.CharField(default='no_username_provided', max_length=65),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
