# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswiki', '0012_auto_20180214_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explaination',
            name='date',
            field=models.CharField(default='01-01-1970', max_length=11),
        ),
    ]
