# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-15 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswiki', '0014_auto_20180214_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='createdby',
            field=models.CharField(default='defaultuser', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='createdday',
            field=models.DateField(default='1970-1-1'),
        ),
    ]
