# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-15 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswiki', '0015_auto_20180215_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullExplaination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.IntegerField(default=-1)),
                ('content', models.CharField(default='default', max_length=10000)),
                ('date', models.DateField()),
                ('user', models.CharField(default='defuser', max_length=64)),
                ('page', models.CharField(default=-1, max_length=5)),
                ('karma', models.CharField(default='1', max_length=5)),
                ('votetype', models.CharField(default='neut', max_length=4)),
            ],
        ),
    ]
